### ISSUE TITLE
bad axis2 argument to swapaxes

### ISSUE THREAD

**Issue by MistQue** [jych/nips2015_vrnn#8]
> Entering main loop
> Traceback (most recent call last):
>   File "vrnn_gauss.py", line 371, in <module>
>     main(params)
>   File "vrnn_gauss.py", line 349, in main
>     mainloop.run()
>   File "cle/cle/train/**init**.py", line 83, in run
>     while self.run_epoch():
>   File "cle/cle/train/**init**.py", line 89, in run_epoch
>     for batch in self.data:
>   File "cle/cle/data/**init**.py", line 90, in **iter**
>     yield self.data.slices(idx, idx + self.batch_size)
>   File "../../../nips2015_vrnn/datasets/iamondb.py", line 97, in slices
>     mask = self.create_mask(batches[0].swapaxes(0, 1))
> ValueError: bad axis2 argument to swapaxes

Hi, I run the model of iamondb ,and got the eroor message , how can I fix it ? thx !

**Comment by mjmnzg** [comment]
Hello, I have the same problem. Can you say me if you fixed it? Thanks.

**Comment by MistQue** [comment]
Hi, i rewrite the code of slices function of **iamondb.py** in path **/nips2015_vrnn/datasets**

```
  def slices(self, start, end):
      batches = [mat[start:end] for mat in self.data]
      label_batches = [mat[start:end] for mat in self.labels]
      #mask = self.create_mask(batches[0].swapaxes(0, 1))
      len_batches = len(batches[0].shape)
      if(len_batches <= 1):
        mask = self.create_mask(batches[0])
      else:
        mask = self.create_mask(batches[0].swapaxes(0, 1))
      batches = [self.zero_pad(batch) for batch in batches]
      #label_mask = self.create_mask(label_batches[0].swapaxes(0, 1))
      len_label_batches = len(label_batches[0].shape)
      if(len_label_batches <= 1):
        label_mask = self.create_mask(label_batches[0])
      else:
        label_mask = self.create_mask(label_batches[0].swapaxes(0, 1))
      label_batches = [self.zero_pad(batch) for batch in label_batches]

      if self.cond:
          return totuple([batches[0], mask, label_batches[0], label_mask])
      else:
          return totuple([batches[0], mask])
```

**Comment by mjmnzg** [comment]
Thank very much for your help! It works! Now, I'm happy. 
Best regards!.

**Comment by DongGuangchang** [comment]
Dear Xin Yang
I saw that you used Mr. Yaseen's program about the recurrent neural networkhttps on the site ：//github.com/uyaseen/theano-recurrence/issues/1，I also used this procedure, but encountered some problems, would like to ask you.
I encountered some difficulties when debugging your program on recurrent neural networks:
first, it has a error when debugging sample.py . ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
data size: 49388, vocab size: 75
train(..)
load_data(..)
[Train] # of rows: 987
... transferring data to the GPU
Traceback (most recent call last):
... building the model
File "F:/DL-File/RNN/theano-recurrence-b9b8a82410be005d5a3121345e8d62c5ca547982/train.py", line 145, in
n_h=100, use_existing_model=True, n_epochs=600)
File "F:/DL-File/RNN/theano-recurrence-b9b8a82410be005d5a3121345e8d62c5ca547982/train.py", line 50, in train
rec_params = pkl.load(f)
EOFError
***
Second, it has a error when debugging train.py .
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (outputs_info in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 2) has dtype int32, while the result of the inner function (fn) has dtype int64. This can happen if the inner function of scan results in an upcast or downcast.
I hope you help explain the reasons for the above mistakes。Thank you very much！
Thanks,
Liang Dong

**Comment by gissemari** [comment]
I'm having the same error but I would like to know why the swap/mask is done so I can apply the correction with any other concern.
